{ lib, pkgs, ... }:
let
  forgejoUrl = "https://git.johnwilger.com";
  ciStateDir = "/var/lib/forgejo-runner";
  releaseStateDir = "/var/lib/forgejo-runner-release";
  cacheDir = "/var/cache/forgejo-runner-nix";
  dindRunDir = "/run/forgejo-runner-dind";
  dindStateDir = "/var/lib/forgejo-runner-dind";
  dindSocket = "${dindRunDir}/docker.sock";
  dindContainerName = "forgejo-runner-dind";
  dindImage = "docker.io/library/docker:27-dind";
  package = pkgs.forgejo-runner;
  dindExecStart = lib.concatStringsSep " " [
    "${pkgs.docker}/bin/docker"
    "run"
    "--rm"
    "--name=${dindContainerName}"
    "--privileged"
    "--network=bridge"
    "--env=DOCKER_TLS_CERTDIR="
    "--volume=${dindRunDir}:${dindRunDir}"
    "--volume=${dindStateDir}:/var/lib/docker"
    dindImage
    "dockerd"
    "--host=unix://${dindSocket}"
    "--data-root=/var/lib/docker"
    "--pidfile=${dindRunDir}/docker.pid"
  ];
  runnerPath = [
    pkgs.bash
    pkgs.cacert
    pkgs.coreutils
    pkgs.curl
    pkgs.docker
    pkgs.gawk
    pkgs.git
    pkgs.gnused
    pkgs.jq
    pkgs.openssh
  ];

  # Static skeleton config. Connection (url/uuid/token) is appended at
  # startup from secret files in stateDir so credentials never land in
  # /nix/store. forgejo-runner v12+ no longer uses a `register` step or
  # a .runner state file — the (uuid, token) pair lives directly in
  # config.yaml under server.connections, generated by Forgejo 15's
  # "Create new Runner" admin UI.
  ciConfigSkeleton = pkgs.writeText "forgejo-runner-ci-config-skeleton.yaml" ''
    log:
      level: info
    runner:
      capacity: 2
      timeout: 3h
      labels:
        - ubuntu-24.04:docker://docker.io/gitea/runner-images:ubuntu-24.04
    cache:
      enabled: false
    container:
      # Persist /nix across container jobs so flake-based builds reuse a
      # warm store instead of rebuilding from scratch every run.
      # valid_volumes is the runner's allowlist — without it, options'
      # bind mount is silently dropped.
      valid_volumes:
        - ${cacheDir}
      options: -v ${cacheDir}:/nix
      privileged: false
      force_pull: false
  '';

  releaseConfigSkeleton = pkgs.writeText "forgejo-runner-release-config-skeleton.yaml" ''
    log:
      level: info
    runner:
      capacity: 1
      timeout: 3h
      labels:
        - docker-release:docker://docker.io/gitea/runner-images:ubuntu-24.04
    cache:
      enabled: false
    container:
      docker_host: unix://${dindSocket}
      privileged: true
      force_pull: false
  '';

  mkRunnerPreStart =
    {
      stateDir,
      configSkeleton,
      serviceName,
      extra ? "",
    }:
    ''
      set -e
      cd ${stateDir}
      if [ ! -s uuid ] || [ ! -s token ]; then
        echo "ERROR: ${stateDir}/uuid and ${stateDir}/token must be non-empty." >&2
        echo "Create the runner at ${forgejoUrl}/-/admin/actions/runners" >&2
        echo "(Create new Runner), then:" >&2
        echo "  printf '%s' '<UUID>'  | sudo tee ${stateDir}/uuid" >&2
        echo "  printf '%s' '<TOKEN>' | sudo tee ${stateDir}/token" >&2
        echo "  sudo chown ${serviceName}:${serviceName} ${stateDir}/{uuid,token}" >&2
        echo "  sudo chmod 0400 ${stateDir}/{uuid,token}" >&2
        echo "  sudo systemctl restart ${serviceName}" >&2
        exit 1
      fi
      ${extra}
      UUID=$(cat uuid)
      TOKEN=$(cat token)
      umask 077
      cp ${configSkeleton} config.yaml
      chmod u+w config.yaml
      cat >> config.yaml <<EOF
      server:
        connections:
          forgejo:
            url: ${forgejoUrl}
            uuid: $UUID
            token: $TOKEN
      EOF
    '';

  mkRunnerService =
    {
      description,
      stateDir,
      configSkeleton,
      serviceName,
      user,
      group,
      after ? [
        "network-online.target"
        "docker.service"
      ],
      wants ? [ "network-online.target" ],
      requires ? [ "docker.service" ],
      preStartExtra ? "",
    }:
    {
      inherit
        after
        description
        requires
        wants
        ;
      wantedBy = [ "multi-user.target" ];

      path = runnerPath;

      preStart = mkRunnerPreStart {
        inherit configSkeleton serviceName stateDir;
        extra = preStartExtra;
      };

      # Cap restart loop so a missing/bad credential surfaces as `failed`
      # instead of burning CPU forever.
      startLimitIntervalSec = 60;
      startLimitBurst = 3;

      serviceConfig = {
        Type = "simple";
        User = user;
        Group = group;
        WorkingDirectory = stateDir;
        ExecStart = "${package}/bin/forgejo-runner daemon --config ${stateDir}/config.yaml";
        Restart = "on-failure";
        RestartSec = lib.mkForce "10s";
      };
    };
in
{
  users.users.forgejo-runner = {
    isSystemUser = true;
    group = "forgejo-runner";
    extraGroups = [ "docker" ];
    home = ciStateDir;
    createHome = false;
  };

  users.users.forgejo-runner-release = {
    isSystemUser = true;
    group = "forgejo-runner-release";
    home = releaseStateDir;
    createHome = false;
  };

  users.groups.forgejo-runner = { };
  users.groups.forgejo-runner-release = { };

  systemd.tmpfiles.rules = [
    "d ${ciStateDir} 0700 forgejo-runner forgejo-runner -"
    "d ${releaseStateDir} 0700 forgejo-runner-release forgejo-runner-release -"
    "d ${dindRunDir} 0750 root forgejo-runner-release -"
    "d ${dindStateDir} 0700 root root -"
    "d ${cacheDir} 0755 root root -"
  ];

  systemd.services.forgejo-runner-dind = {
    description = "Forgejo Release Runner Docker-in-Docker Daemon";
    after = [
      "docker.service"
    ];
    path = [
      pkgs.coreutils
      pkgs.docker
    ];
    requires = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];

    preStart = ''
      install -d -m 0750 -o root -g forgejo-runner-release ${dindRunDir}
      install -d -m 0700 -o root -g root ${dindStateDir}
      rm -f ${dindSocket}
      docker rm -f ${dindContainerName} >/dev/null 2>&1 || true
    '';

    postStart = ''
      i=0
      while [ "$i" -lt 60 ]; do
        if [ -S ${dindSocket} ]; then
          chown root:forgejo-runner-release ${dindSocket}
          chmod 0660 ${dindSocket}
          exit 0
        fi
        i=$((i + 1))
        sleep 1
      done
      echo "ERROR: timed out waiting for ${dindSocket}" >&2
      exit 1
    '';

    serviceConfig = {
      Type = "simple";
      ExecStart = dindExecStart;
      ExecStop = "-${pkgs.docker}/bin/docker stop ${dindContainerName}";
      Restart = "on-failure";
      RestartSec = lib.mkForce "10s";
    };
  };

  systemd.services.forgejo-runner = mkRunnerService {
    description = "Forgejo Actions CI Runner";
    stateDir = ciStateDir;
    configSkeleton = ciConfigSkeleton;
    serviceName = "forgejo-runner";
    user = "forgejo-runner";
    group = "forgejo-runner";
  };

  systemd.services.forgejo-runner-release = mkRunnerService {
    description = "Forgejo Actions Release Runner";
    stateDir = releaseStateDir;
    configSkeleton = releaseConfigSkeleton;
    serviceName = "forgejo-runner-release";
    user = "forgejo-runner-release";
    group = "forgejo-runner-release";
    after = [
      "network-online.target"
      "forgejo-runner-dind.service"
    ];
    wants = [ "network-online.target" ];
    requires = [ "forgejo-runner-dind.service" ];
    preStartExtra = ''
      i=0
      while [ "$i" -lt 60 ]; do
        if [ -S ${dindSocket} ] && [ -r ${dindSocket} ] && [ -w ${dindSocket} ]; then
          break
        fi
        i=$((i + 1))
        sleep 1
      done
      if [ "$i" -eq 60 ]; then
        echo "ERROR: ${dindSocket} is not ready for forgejo-runner-release." >&2
        exit 1
      fi
    '';
  };
}
