{ lib, pkgs, ... }:
let
  forgejoUrl = "https://git.johnwilger.com";
  ciStateDir = "/var/lib/forgejo-runner";
  releaseStateDir = "/var/lib/forgejo-runner-release";
  cacheDir = "/var/cache/forgejo-runner-nix";
  cacheStoreUrl = "local?real=${cacheDir}/store&state=${cacheDir}/var/nix&log=${cacheDir}/var/log/nix";
  dindRunDir = "/run/forgejo-runner-dind";
  dindStateDir = "/var/lib/forgejo-runner-dind";
  dindSocket = "${dindRunDir}/docker.sock";
  dindContainerName = "forgejo-runner-dind";
  dindNetworkName = "forgejo-runner-dind";
  dindImage = "docker.io/library/docker:27-dind";
  package = pkgs.forgejo-runner;
  dindExecStart = lib.concatStringsSep " " [
    "${pkgs.docker}/bin/docker"
    "run"
    "--rm"
    "--name=${dindContainerName}"
    "--privileged"
    "--network=${dindNetworkName}"
    "--env=DOCKER_TLS_CERTDIR="
    "--volume=${dindRunDir}:${dindRunDir}"
    "--volume=${dindStateDir}:/var/lib/docker"
    # The Docker daemon runs inside this DinD container. Bind the host Nix
    # cache at the same absolute path so job containers created by that daemon
    # can mount ${cacheDir}:/nix from the daemon's filesystem namespace.
    "--volume=${cacheDir}:${cacheDir}"
    dindImage
    "dockerd"
    "--host=unix://${dindSocket}"
    "--data-root=/var/lib/docker"
    "--pidfile=${dindRunDir}/docker.pid"
  ];
  runnerPath = [
    pkgs.bash
    pkgs.cacert
    pkgs.coreutils
    pkgs.curl
    pkgs.docker
    pkgs.gawk
    pkgs.git
    pkgs.gnused
    pkgs.jq
    pkgs.openssh
  ];

  # Static skeleton config. Connection (url/uuid/token) is appended at
  # startup from secret files in stateDir so credentials never land in
  # /nix/store. forgejo-runner v12+ no longer uses a `register` step or
  # a .runner state file — the (uuid, token) pair lives directly in
  # config.yaml under server.connections, generated by Forgejo 15's
  # "Create new Runner" admin UI.
  ciConfigSkeleton = pkgs.writeText "forgejo-runner-ci-config-skeleton.yaml" ''
    log:
      level: info
    runner:
      capacity: 2
      timeout: 3h
      labels:
        - ubuntu-24.04:docker://docker.io/gitea/runner-images:ubuntu-24.04
    cache:
      enabled: false
    container:
      # Persist /nix across container jobs so flake-based builds reuse a
      # warm store instead of rebuilding from scratch every run.
      # valid_volumes is the runner's allowlist — without it, options'
      # bind mount is silently dropped.
      valid_volumes:
        - ${cacheDir}
      options: -v ${cacheDir}:/nix
      privileged: false
      force_pull: false
  '';

  releaseConfigSkeleton = pkgs.writeText "forgejo-runner-release-config-skeleton.yaml" ''
    log:
      level: info
    runner:
      capacity: 1
      timeout: 3h
      labels:
        - docker-release:docker://docker.io/gitea/runner-images:ubuntu-24.04
    cache:
      enabled: false
    container:
      docker_host: unix://${dindSocket}
      # Release jobs use Docker-in-Docker. The DinD daemon also mounts
      # ${cacheDir} at this path, so this bind reaches the same persistent
      # store used by the ordinary CI runner.
      valid_volumes:
        - ${cacheDir}
      options: -v ${cacheDir}:/nix
      privileged: true
      force_pull: false
  '';

  mkRunnerPreStart =
    {
      stateDir,
      configSkeleton,
      serviceName,
      extra ? "",
    }:
    ''
      set -e
      cd ${stateDir}
      if [ ! -s uuid ] || [ ! -s token ]; then
        echo "ERROR: ${stateDir}/uuid and ${stateDir}/token must be non-empty." >&2
        echo "Create the runner at ${forgejoUrl}/-/admin/actions/runners" >&2
        echo "(Create new Runner), then:" >&2
        echo "  printf '%s' '<UUID>'  | sudo tee ${stateDir}/uuid" >&2
        echo "  printf '%s' '<TOKEN>' | sudo tee ${stateDir}/token" >&2
        echo "  sudo chown ${serviceName}:${serviceName} ${stateDir}/{uuid,token}" >&2
        echo "  sudo chmod 0400 ${stateDir}/{uuid,token}" >&2
        echo "  sudo systemctl restart ${serviceName}" >&2
        exit 1
      fi
      ${extra}
      # Wait for Forgejo to be reachable before the runner calls Declare.
      # On a co-restart (e.g. nixos-rebuild) the runner can start before
      # Forgejo's backend is up, and the reverse proxy answers 502.
      i=0
      while [ "$i" -lt 60 ]; do
        code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 \
          ${forgejoUrl}/api/healthz || echo 000)
        if [ "$code" = "200" ]; then
          break
        fi
        i=$((i + 1))
        sleep 2
      done
      if [ "$i" -eq 60 ]; then
        echo "ERROR: ${forgejoUrl} not reachable (last status $code)." >&2
        exit 1
      fi
      UUID=$(cat uuid)
      TOKEN=$(cat token)
      umask 077
      cp ${configSkeleton} config.yaml
      chmod u+w config.yaml
      cat >> config.yaml <<EOF
      server:
        connections:
          forgejo:
            url: ${forgejoUrl}
            uuid: $UUID
            token: $TOKEN
      EOF
    '';

  mkRunnerService =
    {
      description,
      stateDir,
      configSkeleton,
      serviceName,
      user,
      group,
      after ? [
        "network-online.target"
        "docker.service"
        "forgejo.service"
      ],
      wants ? [ "network-online.target" ],
      requires ? [ "docker.service" ],
      preStartExtra ? "",
    }:
    {
      inherit
        after
        description
        requires
        wants
        ;
      unitConfig.RequiresMountsFor = [ cacheDir ];
      wantedBy = [ "multi-user.target" ];

      path = runnerPath;

      preStart = mkRunnerPreStart {
        inherit configSkeleton serviceName stateDir;
        extra = preStartExtra;
      };

      # Cap restart loop so a missing/bad credential surfaces as `failed`
      # instead of burning CPU forever.
      startLimitIntervalSec = 60;
      startLimitBurst = 3;

      serviceConfig = {
        Type = "simple";
        User = user;
        Group = group;
        WorkingDirectory = stateDir;
        ExecStart = "${package}/bin/forgejo-runner daemon --config ${stateDir}/config.yaml";
        Restart = "on-failure";
        RestartSec = lib.mkForce "10s";
      };
    };
in
{
  users.users.forgejo-runner = {
    isSystemUser = true;
    group = "forgejo-runner";
    extraGroups = [ "docker" ];
    home = ciStateDir;
    createHome = false;
  };

  users.users.forgejo-runner-release = {
    isSystemUser = true;
    group = "forgejo-runner-release";
    home = releaseStateDir;
    createHome = false;
  };

  users.groups.forgejo-runner = { };
  users.groups.forgejo-runner-release = { };

  systemd.tmpfiles.rules = [
    "d ${ciStateDir} 0700 forgejo-runner forgejo-runner -"
    "d ${releaseStateDir} 0700 forgejo-runner-release forgejo-runner-release -"
    "d ${dindRunDir} 0750 root forgejo-runner-release -"
    "d ${dindStateDir} 0700 root root -"
    "d ${cacheDir} 0755 root root -"
  ];

  systemd.services.forgejo-runner-dind = {
    description = "Forgejo Release Runner Docker-in-Docker Daemon";
    after = [
      "docker.service"
    ];
    path = [
      pkgs.coreutils
      pkgs.docker
    ];
    requires = [ "docker.service" ];
    unitConfig.RequiresMountsFor = [
      cacheDir
      dindStateDir
    ];
    wantedBy = [ "multi-user.target" ];

    preStart = ''
      install -d -m 0750 -o root -g forgejo-runner-release ${dindRunDir}
      install -d -m 0700 -o root -g root ${dindStateDir}
      rm -f ${dindSocket}
      docker network inspect ${dindNetworkName} >/dev/null 2>&1 \
        || docker network create ${dindNetworkName} >/dev/null
      docker rm -f ${dindContainerName} >/dev/null 2>&1 || true
    '';

    postStart = ''
      i=0
      while [ "$i" -lt 60 ]; do
        if [ -S ${dindSocket} ]; then
          chown root:forgejo-runner-release ${dindSocket}
          chmod 0660 ${dindSocket}
          exit 0
        fi
        i=$((i + 1))
        sleep 1
      done
      echo "ERROR: timed out waiting for ${dindSocket}" >&2
      exit 1
    '';

    serviceConfig = {
      Type = "simple";
      ExecStart = dindExecStart;
      ExecStop = "-${pkgs.docker}/bin/docker stop ${dindContainerName}";
      Restart = "on-failure";
      RestartSec = lib.mkForce "10s";
    };
  };

  systemd.services.forgejo-runner-nix-cache-gc = {
    description = "Garbage collect Forgejo runner nested Nix store";
    unitConfig.RequiresMountsFor = [ cacheDir ];
    path = [
      pkgs.nix
      pkgs.coreutils
    ];
    serviceConfig = {
      Type = "oneshot";
      IOSchedulingClass = "idle";
      Nice = 19;
    };
    # Size-gated GC. The old behaviour ran an unconditional `nix store gc`,
    # which deletes every path not reachable from a GC root. CI uses
    # `nix develop` / `nix build`, which leave NO persistent roots, so the
    # warm dev-shell closures (nodejs, rust, …) were wiped every night.
    # Job containers can neither rebuild (sandbox refuses the world-writable
    # container `/`) nor reliably substitute, so the next CI run failed
    # realizing whatever the sweep had just evicted.
    #
    # The store now lives on its own ${cacheDir} disk (its own spindle, not
    # the NVMe the GC was originally added to relieve), so a nightly wipe to
    # reclaim a few hundred MiB is all cost and no benefit. Instead: only
    # collect once the store grows past a budget, and then only trim the
    # excess with `--max` so most of the warm set survives. At normal size
    # this is a no-op and the warm closures persist indefinitely.
    script = ''
      budget=$(( 50 * 1024 * 1024 * 1024 ))   # collect only above 50 GiB
      target=$(( 40 * 1024 * 1024 * 1024 ))   # trim back down toward 40 GiB
      size=$(du -sb '${cacheDir}/store' | cut -f1)
      if [ "$size" -gt "$budget" ]; then
        free=$(( size - target ))
        echo "nested store is $size bytes (> $budget); freeing up to $free bytes"
        nix store gc --store '${cacheStoreUrl}' --max "$free"
      else
        echo "nested store is $size bytes (<= $budget); skipping GC"
      fi
    '';
  };

  systemd.timers.forgejo-runner-nix-cache-gc = {
    description = "Daily Forgejo runner nested Nix store garbage collection";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "*-*-* 02:30:00";
      Persistent = true;
      RandomizedDelaySec = "15m";
    };
  };

  systemd.services.forgejo-runner = mkRunnerService {
    description = "Forgejo Actions CI Runner";
    stateDir = ciStateDir;
    configSkeleton = ciConfigSkeleton;
    serviceName = "forgejo-runner";
    user = "forgejo-runner";
    group = "forgejo-runner";
  };

  systemd.services.forgejo-runner-release = mkRunnerService {
    description = "Forgejo Actions Release Runner";
    stateDir = releaseStateDir;
    configSkeleton = releaseConfigSkeleton;
    serviceName = "forgejo-runner-release";
    user = "forgejo-runner-release";
    group = "forgejo-runner-release";
    after = [
      "network-online.target"
      "forgejo-runner-dind.service"
      "forgejo.service"
    ];
    wants = [ "network-online.target" ];
    requires = [ "forgejo-runner-dind.service" ];
    preStartExtra = ''
      i=0
      while [ "$i" -lt 60 ]; do
        if [ -S ${dindSocket} ] && [ -r ${dindSocket} ] && [ -w ${dindSocket} ]; then
          break
        fi
        i=$((i + 1))
        sleep 1
      done
      if [ "$i" -eq 60 ]; then
        echo "ERROR: ${dindSocket} is not ready for forgejo-runner-release." >&2
        exit 1
      fi
    '';
  };
}
