{ lib, pkgs, ... }:
let
  forgejoUrl = "https://git.johnwilger.com";
  stateDir = "/var/lib/forgejo-runner";
  cacheDir = "/var/cache/forgejo-runner-nix";
  package = pkgs.forgejo-runner;

  # Static skeleton config. Connection (url/uuid/token) is appended at
  # startup from secret files in stateDir so credentials never land in
  # /nix/store. forgejo-runner v12+ no longer uses a `register` step or
  # a .runner state file — the (uuid, token) pair lives directly in
  # config.yaml under server.connections, generated by Forgejo 15's
  # "Create new Runner" admin UI.
  configSkeleton = pkgs.writeText "forgejo-runner-config-skeleton.yaml" ''
    log:
      level: info
    runner:
      capacity: 2
      timeout: 3h
      labels:
        - docker:docker://node:20-bookworm
        - native:host
    cache:
      enabled: false
    container:
      # Persist /nix across container jobs so flake-based builds reuse a
      # warm store instead of rebuilding from scratch every run.
      # valid_volumes is the runner's allowlist — without it, options'
      # bind mount is silently dropped.
      #
      # Use host networking so job containers can reach services bound on
      # the runner host, including the auto_review dev gateway on
      # localhost:8090. Per-job bridge networks would otherwise isolate
      # them from those host services.
      valid_volumes:
        - ${cacheDir}
      options: -v ${cacheDir}:/nix --network host
      privileged: false
      force_pull: false
  '';
in
{
  users.users.forgejo-runner = {
    isSystemUser = true;
    group = "forgejo-runner";
    extraGroups = [ "docker" ];
    home = stateDir;
    createHome = false;
  };
  users.groups.forgejo-runner = { };

  systemd.tmpfiles.rules = [
    "d ${stateDir} 0700 forgejo-runner forgejo-runner -"
    "d ${cacheDir} 0755 root root -"
  ];

  systemd.services.forgejo-runner = {
    description = "Forgejo Actions Runner";
    after = [
      "network-online.target"
      "docker.service"
    ];
    wants = [ "network-online.target" ];
    requires = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];

    path = [
      pkgs.docker
      pkgs.git
      pkgs.bash
      pkgs.coreutils
      pkgs.openssh
    ];

    preStart = ''
      set -e
      cd ${stateDir}
      if [ ! -s uuid ] || [ ! -s token ]; then
        echo "ERROR: ${stateDir}/uuid and ${stateDir}/token must be non-empty." >&2
        echo "Create the runner at ${forgejoUrl}/-/admin/actions/runners" >&2
        echo "(Create new Runner), then:" >&2
        echo "  printf '%s' '<UUID>'  | sudo tee ${stateDir}/uuid" >&2
        echo "  printf '%s' '<TOKEN>' | sudo tee ${stateDir}/token" >&2
        echo "  sudo chown forgejo-runner:forgejo-runner ${stateDir}/{uuid,token}" >&2
        echo "  sudo chmod 0400 ${stateDir}/{uuid,token}" >&2
        echo "  sudo systemctl restart forgejo-runner" >&2
        exit 1
      fi
      UUID=$(cat uuid)
      TOKEN=$(cat token)
      umask 077
      cp ${configSkeleton} config.yaml
      chmod u+w config.yaml
      cat >> config.yaml <<EOF
      server:
        connections:
          forgejo:
            url: ${forgejoUrl}
            uuid: $UUID
            token: $TOKEN
      EOF
    '';

    # Cap restart loop so a missing/bad credential surfaces as `failed`
    # instead of burning CPU forever.
    startLimitIntervalSec = 60;
    startLimitBurst = 3;

    serviceConfig = {
      Type = "simple";
      User = "forgejo-runner";
      Group = "forgejo-runner";
      WorkingDirectory = stateDir;
      ExecStart = "${package}/bin/forgejo-runner daemon --config ${stateDir}/config.yaml";
      Restart = "on-failure";
      RestartSec = lib.mkForce "10s";
    };
  };
}
