{ pkgs, username, ... }:
let
  forgejoUrl = "https://git.johnwilger.com";
  stateDir = "/Users/${username}/Library/forgejo-runner";
  package = pkgs.forgejo-runner;

  # Static skeleton config. Connection (url/uuid/token) is appended at
  # startup from secret files in stateDir so credentials never land in
  # /nix/store. forgejo-runner v12+ no longer uses a `register` step or
  # a .runner state file — the (uuid, token) pair lives directly in
  # config.yaml under server.connections, generated by Forgejo 15's
  # "Create new Runner" admin UI.
  configSkeleton = pkgs.writeText "forgejo-runner-config-skeleton.yaml" ''
    log:
      level: info
    runner:
      capacity: 2
      timeout: 3h
      # No `native:host` label here on purpose: gregor advertises `native`
      # meaning "Linux host", and most workflows tagged that way assume
      # Linux tooling (getent, groupadd, install-nix-action, etc.). On
      # sansa `native` would mean macOS, which silently breaks those
      # workflows. If a workflow genuinely needs macOS-native execution,
      # add an explicit `darwin:host` label here and target it from the
      # workflow with runs-on: darwin.
      labels:
        - docker:docker://node:20-bookworm
    cache:
      enabled: false
    container:
      network: host
      privileged: false
      force_pull: false
    host:
      workdir_parent: ${stateDir}/work
  '';
in
{
  # Per-user LaunchAgent: runs as jwilger after login, which is when
  # Docker Desktop is up and its socket at /var/run/docker.sock is
  # reachable. A system LaunchDaemon would start at boot but couldn't
  # use Docker until login anyway.
  launchd.user.agents.forgejo-runner = {
    path = [
      pkgs.git
      pkgs.bash
      pkgs.coreutils
      pkgs.jq
      pkgs.nix
      pkgs.openssh
    ];
    environment = {
      HOME = "/Users/${username}";
      # Docker Desktop on macOS exposes its socket at ~/.docker/run/docker.sock,
      # not /var/run/docker.sock. (The latter is a stale symlink from a prior
      # OrbStack install pointing at a non-existent target.)
      DOCKER_HOST = "unix:///Users/${username}/.docker/run/docker.sock";
    };
    serviceConfig = {
      Label = "com.forgejo.runner";
      KeepAlive = true;
      RunAtLoad = true;
      WorkingDirectory = stateDir;
      StandardOutPath = "${stateDir}/runner.out.log";
      StandardErrorPath = "${stateDir}/runner.err.log";
    };
    script = ''
      set -e
      echo "[forgejo-runner] starting uid=$(id -u) gid=$(id -g) cwd=$(pwd)" >&2
      mkdir -p ${stateDir}/work
      if [ ! -s ${stateDir}/uuid ] || [ ! -s ${stateDir}/token ]; then
        echo "ERROR: ${stateDir}/uuid and ${stateDir}/token must be non-empty." >&2
        echo "Create the runner at ${forgejoUrl}/-/admin/actions/runners" >&2
        echo "(Create new Runner), then:" >&2
        echo "  printf '%s' '<UUID>'  > ${stateDir}/uuid" >&2
        echo "  printf '%s' '<TOKEN>' > ${stateDir}/token" >&2
        echo "  chmod 600 ${stateDir}/{uuid,token}" >&2
        echo "  launchctl kickstart -k gui/$(id -u)/com.forgejo.runner" >&2
        exit 1
      fi
      # Wait for Docker Desktop's socket. wait4path follows symlinks via
      # stat(), so it blocks until Docker Desktop is actually up. Without
      # this the runner crash-loops at login if Docker Desktop hasn't
      # finished starting yet.
      echo "[forgejo-runner] waiting for /Users/${username}/.docker/run/docker.sock" >&2
      /bin/wait4path /Users/${username}/.docker/run/docker.sock
      echo "[forgejo-runner] docker socket ready" >&2

      DOCKER_CONFIG_JSON=/Users/${username}/.docker/config.json
      if [ -f "$DOCKER_CONFIG_JSON" ] && jq -e 'has("credsStore")' "$DOCKER_CONFIG_JSON" >/dev/null; then
        echo "[forgejo-runner] removing credsStore from $DOCKER_CONFIG_JSON" >&2
        TMP_CONFIG=$(mktemp)
        jq 'del(.credsStore)' "$DOCKER_CONFIG_JSON" > "$TMP_CONFIG"
        install -m 0600 "$TMP_CONFIG" "$DOCKER_CONFIG_JSON"
        rm -f "$TMP_CONFIG"
      fi

      UUID=$(cat ${stateDir}/uuid)
      TOKEN=$(cat ${stateDir}/token)
      umask 077
      rm -f ${stateDir}/config.yaml
      install -m 0600 ${configSkeleton} ${stateDir}/config.yaml
      cat >> ${stateDir}/config.yaml <<EOF
      server:
        connections:
          forgejo:
            url: ${forgejoUrl}
            uuid: $UUID
            token: $TOKEN
      EOF
      exec ${package}/bin/forgejo-runner daemon --config ${stateDir}/config.yaml
    '';
  };
}
