# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "virtio_pci" "usbhid" "usb_storage" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/42e196c9-3c4a-4f1a-9f60-819ba90a3df9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D3B2-1C9D";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  networking.useDHCP = lib.mkDefault true;

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
