# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "sr_mod"
    "usb_storage"
    "virtio_blk"
    "virtio_pci"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f458e5f7-1dfc-44a3-9843-bb36c3015289";
    fsType = "ext4";
  };

  networking.useDHCP = lib.mkDefault true;

  swapDevices = [ ];
}
